>>>> print v.n()
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
AttributeError: n
